spring.data.mongodb.uri=mongodb://localhost:27017/mage
spring.data.mongodb.database=mage
server.error.include-message=always
server.port=8092

appconfig=./src/main/resources/app_config.json
pmsconfig=./src/main/resources/pms_config.json
python=C:/Users/iohkg/miniconda3/envs/dl/python